/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trafego.view;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import trafego.model.AeronaveDao;
import trafego.model.ClasseAeronave;
import trafego.model.ClasseLogin;
import trafego.model.ClasseLoginDao;
import trafego.model.ClasseMenu;

/**
 *
 * @author wesley
 */
public class TelaLogin extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        controller = new LoginController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSenha = new javax.swing.JLabel();
        txtEntradaSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        txtEntradaNome = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("SENHA");
        getContentPane().add(lbSenha);
        lbSenha.setBounds(640, 360, 110, 20);

        txtEntradaSenha.setBackground(new java.awt.Color(0, 0, 0));
        txtEntradaSenha.setForeground(new java.awt.Color(255, 255, 0));
        txtEntradaSenha.setText("jPasswordField1");
        getContentPane().add(txtEntradaSenha);
        txtEntradaSenha.setBounds(590, 390, 180, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("alphabravo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 420, 70, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("nave ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 420, 170, 16);

        lbUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("       USUÁRIO");
        getContentPane().add(lbUsuario);
        lbUsuario.setBounds(110, 360, 130, 20);

        txtEntradaNome.setBackground(new java.awt.Color(0, 0, 0));
        txtEntradaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEntradaNome.setForeground(new java.awt.Color(255, 204, 0));
        txtEntradaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtEntradaNome);
        txtEntradaNome.setBounds(60, 390, 200, 26);

        botaoEntrar.setBackground(new java.awt.Color(0, 0, 0));
        botaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setText("ENTRAR");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrar);
        botaoEntrar.setBounds(330, 450, 120, 30);

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/F163D.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 490);

        setSize(new java.awt.Dimension(817, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNomeActionPerformed

    }//GEN-LAST:event_txtEntradaNomeActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        String codigo;
        codigo = txtEntradaNome.getText();
        ClasseLoginDao loginDao = new ClasseLoginDao();
        boolean status = loginDao.conectar();
        if (status == true) {
            ClasseLogin classeLogin = loginDao.consultar(codigo);
            if (classeLogin == null) {
                JOptionPane.showConfirmDialog(null, "USUARIO NÃO ENCONTRADO NO BANCO DE DADOS ");
            } else {
                txtEntradaNome.setText(classeLogin.getUsuario());
                txtEntradaSenha.setText(classeLogin.getSenha());
                TelaMenu telaMenu = new TelaMenu();
                telaMenu.setVisible(true);
                this.dispose();
                telaMenu.setLocationRelativeTo(null);
            }

            loginDao.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "OPS!!!!FALHA NA CONEXÃO COM BANCO DE DADOS ");
        }

       /** TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.dispose();*/


    }//GEN-LAST:event_botaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtEntradaNome;
    private javax.swing.JPasswordField txtEntradaSenha;
    // End of variables declaration//GEN-END:variables

    private static class LoginController {

        private Object view;

        public LoginController(TelaLogin aThis) {
        }

        private void autenticar() {

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
        }

    }

    public JTextField getTxtEntradaNome() {
        return txtEntradaNome;
    }

    public void setTxtEntradaNome(JTextField txtEntradaNome) {
        this.txtEntradaNome = txtEntradaNome;
    }

    public JPasswordField getTxtEntradaSenha() {
        return txtEntradaSenha;
    }

    public void setTxtEntradaSenha(JPasswordField txtEntradaSenha) {
        this.txtEntradaSenha = txtEntradaSenha;
    }

}
